DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
	ID VARCHAR(255) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	CREATED timestamp NOT NULL,
	MODIFIED timestamp ,
	LAST_LOGIN timestamp NOT NULL,
	TOKEN VARCHAR(255) NOT NULL,
	IS_ACTIVE boolean NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS TELEFONO;
CREATE TABLE TELEFONO(
	ID VARCHAR(255) PRIMARY KEY,
	USUARIO_ID VARCHAR(255) NOT NULL,
	NUMBER VARCHAR(10) NOT NULL,
	CITY_CODE VARCHAR(4) NOT NULL,
	COUNTRY_CODE VARCHAR(4) NOT NULL,
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

DROP TABLE IF EXISTS PARAMETRO;
CREATE TABLE TELEFONO(
	ID VARCHAR(20) PRIMARY KEY,
	VALOR VARCHAR(255) NOT NULL
);

INSERT INTO PARAMETRO(ID, VALOR) VALUES("PASSWORD_PATTERN", "^[a-zA-Z0-9]*$");
